stages:
- build

build:
  stage: build
  image: maven:3.3.9-jdk-8
  script: "mvn clean package"
  artifacts:
    name: "UltimateStacker Legacy"
    paths:
    - "/builds/Songoda/UltimateStacker/target/*.jar"
    - "/builds/Songoda/UltimateStacker/Read_this_before_your_first_use.txt"
