name: UltimateStacker
description: UltimateStacker
version: maven-version-number
soft-depend: [Arconix]
main: com.songoda.ultimatestacker.UltimateStacker
author: songoda
commands:
  UltimateStacker:
    description: I have no idea.
    default: true
    aliases: [us]
    usage: /<command> [reload]