name: UltimateStacker
description: UltimateStacker
version: maven-version-number
softdepend: [Arconix, HolographicDisplays, WorldGuard, EpicSpawners]
main: com.songoda.ultimatestacker.UltimateStacker
author: songoda
commands:
  UltimateStacker:
    description: I have no idea.
    default: true
    aliases: [us]
    usage: /<command> [reload]